#!/bin/bash




USERNAME=$(whoami)

DATE=$(date +"%Y-%m-%d %H:%M:%S")

HOSTNAME=$(hostname)

DISTRO=$(cat /etc/*-release | grep PRETTY_NAME | cut -d "=" -f 2 | tr -d '"')

UPTIME=$(uptime -p)




CPU=$(lscpu | grep "Model name" | cut -d ":" -f 2 | xargs)

CPU_SPEED=$(lscpu | grep "CPU max MHz" | cut -d ":" -f 2 | xargs) 

RAM=$(free -h | awk '/^Mem:/{print $2}')

DISKS=$(lsblk | grep disk | awk '{print $1, $4}')

VIDEO_CARD=$(lspci | grep -i vga | cut -d ":" -f 3 | xargs)




FQDN=$(hostname -f)

IP_ADDRESS=$(hostname -I)

GATEWAY=$(ip route | awk '/default via/ {print $3}')

DNS_SERVER=$(systemd-resolve --status | awk '/DNS Servers/{print $3}')




INTERFACE_NAME=$(ip link show | awk '/^[0-9]/{print $2}' | tr -d :)

IP_CIDR=$(ip addr show | awk '/inet /{print $2}')




USERS_LOGGED_IN=$(who | awk '{print $1}' | sort -u | tr '\n' ',')

DISK_SPACE=$(df -h --output=target,avail | awk 'NR>1{print $1, $2}')

PROCESS_COUNT=$(ps -A --no-headers | wc -l)

LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1, $2, $3}')

MEMORY_ALLOCATION=$(free -h)

LISTENING_PORTS=$(ss -tuln4 | awk 'NR>1{print $4}' | cut -d ":" -f 2)

UFW_RULES=$(ufw status)




cat << EOF


System Report generated by $USERNAME, $DATE


System Information

------------------

Hostname: $HOSTNAME

OS: $DISTRO

Uptime: $UPTIME


Hardware Information

--------------------

CPU: $CPU

Speed: $CPU_SPEED MHz

RAM: $RAM

Disks: $DISKS

Video: $VIDEO_CARD


Network Information

-------------------

FQDN: $FQDN

Host Address: $IP_ADDRESS

Gateway IP: $GATEWAY

DNS Server: $DNS_SERVER


Interface Information

---------------------

Interface Name: $INTERFACE_NAME

IP Address: $IP_CIDR


System Status

-------------

Users Logged In: ${USERS_LOGGED_IN%,}

Disk Space:

$DISK_SPACE

Process Count: $PROCESS_COUNT

Load Averages: $LOAD_AVERAGES

Memory Allocation:

$MEMORY_ALLOCATION

Listening Network Ports: ${LISTENING_PORTS// /, }

UFW Rules:

$UFW_RULES


EOF
